version: '1.0'
services:
  frontend:
    image: servco/frontend
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    ports:
      - "${WEB_PORT:-3000}:3000"
    volumes:
      - ./client:/usr/src/app/client
    stdin_open: true
    tty: true
    container_name: servco_frontend_container
  backend:
    image: servco/backend
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-5000}:5000"
    volumes:
      - ./server:/usr/src/app/server
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://db:27017/mern-starter
    stdin_open: true
    tty: true
    container_name: servco_frontend_backend
  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
volumes:
  dbdata: